server:
  port: 8081
  servlet:
    context-path: /statisticsService

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

crud:
  rabbitmq:
    exchange: crud.exchange
    queueCaso: crud.consumo.caso